#!/bin/bash

# AVAILABLE OPTIONS
S_BOLD='\033[1m'
S_NORMAL='\033[0m'
C_RED='\033[0;31m'
C_NONE='\033[0m' # No Color

printf "${S_BOLD}Begining init script...${S_NORMAL}\n"

printf "${S_BOLD}Terraform linting...${S_NORMAL}\n"

terraform fmt -check

if [ $? -ne 0 ];
then
  printf "${C_RED}Linting failed. ${C_NONE}\n"
  printf "${C_RED}Please run '${S_BOLD}terraform fmt${S_NORMAL}' on the repository. ${C_NONE}\n"
  exit 1
fi

# shellcheck disable=SC2154
if [ ! -f "${pwd}/state-credentials-custom.tf" ];
then
  printf "${S_BOLD}Generating default 'state-credentials.tf' file...${S_NORMAL}\n"
  cp /usr/state-credentials.tf .
else
  printf "${S_BOLD}Use 'state-credentials-custom.tf' file from repository...${S_NORMAL}\n"
  cp /usr/state-credentials-custom.tf state-credentials.tf
fi

########
# By AWS account `name` with `region` variable
#
# Like: `account1.dev.us-east-1.tfvars`
if [ -f ${TF_VAR_aws_account_name}.${TF_VAR_environment}.${AWS_REGION}.tfvars ];
then
  printf "${S_BOLD}Using "${S_BOLD}${TF_VAR_aws_account_name}.${TF_VAR_environment}.${AWS_REGION}.tfvars${S_NORMAL}" Terraform variable file${S_NORMAL}\n"
  cp ${TF_VAR_aws_account_name}.${TF_VAR_environment}.${AWS_REGION}.tfvars ${TF_VAR_aws_account_name}.${TF_VAR_environment}.${AWS_REGION}.auto.tfvars

########
# By AWS account `name` variable
#
# Like: `tfvars/account1.dev.tfvars`
elif [ -f tfvars/${TF_VAR_aws_account_name}.${TF_VAR_environment}.tfvars ];
then
  printf "${S_BOLD}Using "${S_BOLD}tfvars/${TF_VAR_aws_account_name}.${TF_VAR_environment}.tfvars${S_NORMAL}" Terraform variable file${S_NORMAL}\n"
  cp tfvars/${TF_VAR_aws_account_name}.${TF_VAR_environment}.tfvars ${TF_VAR_aws_account_name}.${TF_VAR_environment}.auto.tfvars

# Like: `account1-dev.tfvars`
elif [ -f ${TF_VAR_aws_account_name}-${TF_VAR_environment}.tfvars ];
then
  printf "${S_BOLD}Using "${S_BOLD}${TF_VAR_aws_account_name}-${TF_VAR_environment}.tfvars${S_NORMAL}" Terraform variable file${S_NORMAL}\n"
  cp ${TF_VAR_aws_account_name}-${TF_VAR_environment}.tfvars ${TF_VAR_aws_account_name}-${TF_VAR_environment}.auto.tfvars

# Like: `account1.dev.tfvars`
elif [ -f ${TF_VAR_aws_account_name}.${TF_VAR_environment}.tfvars ];
then
  printf "${S_BOLD}Using "${S_BOLD}${TF_VAR_aws_account_name}.${TF_VAR_environment}.tfvars${S_NORMAL}" Terraform variable file${S_NORMAL}\n"
  cp ${TF_VAR_aws_account_name}.${TF_VAR_environment}.tfvars ${TF_VAR_aws_account_name}.${TF_VAR_environment}.auto.tfvars

########
# Legacy: By AWS account `type` variable
#
# Like: `tfvars/account1.dev.tfvars`
elif [ -f tfvars/${TF_VAR_account_type}.${TF_VAR_environment}.tfvars ];
then
  printf "${S_BOLD}Using "${S_BOLD}tfvars/${TF_VAR_account_type}.${TF_VAR_environment}.tfvars${S_NORMAL}" Terraform variable file${S_NORMAL}\n"
  cp tfvars/${TF_VAR_account_type}.${TF_VAR_environment}.tfvars ${TF_VAR_account_type}.${TF_VAR_environment}.auto.tfvars

# Like: `account1-dev.tfvars`
elif [ -f ${TF_VAR_account_type}-${TF_VAR_environment}.tfvars ];
then
  printf "${S_BOLD}Using "${S_BOLD}${TF_VAR_account_type}-${TF_VAR_environment}.tfvars${S_NORMAL}" Terraform variable file${S_NORMAL}\n"
  cp ${TF_VAR_account_type}-${TF_VAR_environment}.tfvars ${TF_VAR_account_type}-${TF_VAR_environment}.auto.tfvars

# Like: `account1.dev.tfvars`
elif [ -f ${TF_VAR_account_type}.${TF_VAR_environment}.tfvars ];
then
  printf "${S_BOLD}Using "${S_BOLD}${TF_VAR_account_type}.${TF_VAR_environment}.tfvars${S_NORMAL}" Terraform variable file${S_NORMAL}\n"
  cp ${TF_VAR_account_type}.${TF_VAR_environment}.tfvars ${TF_VAR_account_type}.${TF_VAR_environment}.auto.tfvars
fi

printf "${S_BOLD}Finished Before init script.${S_NORMAL}\n"
